<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <NoWarn>$(NoWarn);10012</NoWarn>
    </PropertyGroup>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MudBlazor" Version="9.*" />
    </ItemGroup>
</Project>
